package com.forwork.backend.api.member.entity;

import lombok.Getter;

@Getter
public enum Nationality {
    GHANA("GHANA", "Ghana", "가나"),
    GABON("GABON", "Gabon", "가봉"),
    GUYANA("GUYANA", "Guyana", "가이아나"),
    GAMBIA("GAMBIA", "Gambia", "감비아"),
    GUATEMALA("GUATEMALA", "Guatemala", "과테말라"),
    GRENADA("GRENADA", "Grenada", "그레나다"),
    GREECE("GREECE", "Greece", "그리스"),
    GUINEA("GUINEA", "Guinea", "기니"),
    GUINEA_BISSAU("GUINEA_BISSAU", "Guinea-Bissau", "기니비사우"),
    NAMIBIA("NAMIBIA", "Namibia", "나미비아"),
    NAURU("NAURU", "Nauru", "나우루"),
    NIGERIA("NIGERIA", "Nigeria", "나이지리아"),
    REPUBLIC_OF_SOUTH_SUDAN("REPUBLIC_OF_SOUTH_SUDAN", "Republic Of South Sudan", "남수단"),
    SOUTH_AFRICA("SOUTH_AFRICA", "South Africa", "남아프리카 공화국"),
    REPUBLIC_OF_SOUTH_OSSETIA("REPUBLIC_OF_SOUTH_OSSETIA", "Republic Of South Ossetia", "남오세티야"),
    NETHERLANDS("NETHERLANDS", "Netherlands", "네덜란드"),
    NEPAL("NEPAL", "Nepal", "네팔"),
    NORWAY("NORWAY", "Norway", "노르웨이"),
    NEW_ZEALAND("NEW_ZEALAND", "New Zealand", "뉴질랜드"),
    NIGER("NIGER", "Niger", "니제르"),
    NICARAGUA("NICARAGUA", "Nicaragua", "니카라과"),
    KOREA_REPUBLIC_OF("KOREA_REPUBLIC_OF", "Korea, Republic Of", "대한민국"),
    TAIWAN("TAIWAN", "Taiwan", "대만"),
    DENMARK("DENMARK", "Denmark", "덴마크"),
    DOMINICAN_REPUBLIC("DOMINICAN_REPUBLIC", "Dominican Republic", "도미니카 공화국"),
    DOMINICA("DOMINICA", "Dominica", "도미니카 연방"),
    GERMANY("GERMANY", "Germany", "독일"),
    EAST_TIMOR("EAST_TIMOR", "East Timor", "동티모르"),
    LAO_PEOPLE_DEMOCRATIC_REPUBLIC("LAO_PEOPLE_DEMOCRATIC_REPUBLIC", "Lao People’s Democratic Republic", "라오스"),
    LIBERIA("LIBERIA", "Liberia", "라이베리아"),
    LATVIA("LATVIA", "Latvia", "라트비아"),
    RUSSIAN_FEDERATION("RUSSIAN_FEDERATION", "Russian Federation", "러시아"),
    LEBANON("LEBANON", "Lebanon", "레바논"),
    LESOTHO("LESOTHO", "Lesotho", "레소토"),
    ROMANIA("ROMANIA", "Romania", "루마니아"),
    LUXEMBOURG("LUXEMBOURG", "Luxembourg", "룩셈부르크"),
    RWANDA("RWANDA", "Rwanda", "르완다"),
    LIBYAN_ARAB_JAMAHIRIYA("LIBYAN_ARAB_JAMAHIRIYA", "Libyan Arab Jamahiriya", "리비아"),
    REPUBLIC_OF_LITHUANIA("REPUBLIC_OF_LITHUANIA", "Republic of Lithuania", "리투아니아"),
    LIECHTENSTEIN("LIECHTENSTEIN", "Liechtenstein", "리히텐슈타인"),
    MADAGASCAR("MADAGASCAR", "Madagascar", "마다가스카르"),
    MARSHALL_ISLANDS("MARSHALL_ISLANDS", "Marshall Islands", "마셜 제도"),
    MALAWI("MALAWI", "Malawi", "말라위"),
    MALAYSIA("MALAYSIA", "Malaysia", "말레이시아"),
    MALI("MALI", "Mali", "말리"),
    MEXICO("MEXICO", "Mexico", "멕시코"),
    MONACO("MONACO", "Monaco", "모나코"),
    MOROCCO("MOROCCO", "Morocco", "모로코"),
    MAURITIUS("MAURITIUS", "Mauritius", "모리셔스"),
    MAURITANIA("MAURITANIA", "Mauritania", "모리타니"),
    MOZAMBIQUE("MOZAMBIQUE", "Mozambique", "모잠비크"),
    MONTENEGRO("MONTENEGRO", "Montenegro", "몬테네그로"),
    MOLDOVA("MOLDOVA", "Moldova", "몰도바"),
    MALDIVES("MALDIVES", "Maldives", "몰디브"),
    MALTA("MALTA", "Malta", "몰타"),
    MONGOLIA("MONGOLIA", "Mongolia", "몽골"),
    UNITED_STATES("UNITED_STATES", "United States", "미국"),
    MYANMAR("MYANMAR", "Myanmar", "미얀마"),
    FEDERATED_STATES_OF_MICRONESIA("FEDERATED_STATES_OF_MICRONESIA", "Federated States of Micronesia", "미크로네시아 연방"),
    VANUATU("VANUATU", "Vanuatu", "바누아투"),
    BAHRAIN("BAHRAIN", "Bahrain", "바레인"),
    BARBADOS("BARBADOS", "Barbados", "바베이도스"),
    VATICAN_CITY("VATICAN_CITY", "Vatican City", "바티칸"),
    BAHAMAS("BAHAMAS", "Bahamas", "바하마"),
    BANGLADESH("BANGLADESH", "Bangladesh", "방글라데시"),
    BENIN("BENIN", "Benin", "베냉"),
    VENEZUELA("VENEZUELA", "Venezuela", "베네수엘라"),
    VIETNAM("VIETNAM", "Vietnam", "베트남"),
    BELGIUM("BELGIUM", "Belgium", "벨기에"),
    BELARUS("BELARUS", "Belarus", "벨라루스"),
    BELIZE("BELIZE", "Belize", "벨리즈"),
    BOSNIA_AND_HERZEGOVINA("BOSNIA_AND_HERZEGOVINA", "Bosnia and Herzegovina", "보스니아 헤르체고비나"),
    BOTSWANA("BOTSWANA", "Botswana", "보츠와나"),
    BOLIVIA("BOLIVIA", "Bolivia", "볼리비아"),
    BURUNDI("BURUNDI", "Burundi", "부룬디"),
    BURKINA_FASO("BURKINA_FASO", "Burkina Faso", "부르키나파소"),
    BHUTAN("BHUTAN", "Bhutan", "부탄"),
    NORTH_MACEDONIA("NORTH_MACEDONIA", "North Macedonia", "북마케도니아"),
    NORTHERN_CYPRUS("NORTHERN_CYPRUS", "Northern Cyprus", "북키프로스"),
    NORTH_KOREA("NORTH_KOREA", "North Korea", "북한"),
    BULGARIA("BULGARIA", "Bulgaria", "불가리아"),
    BRAZIL("BRAZIL", "Brazil", "브라질"),
    BRUNEI("BRUNEI", "Brunei", "브루나이"),
    SAMOA("SAMOA", "Samoa", "사모아"),
    SAUDI_ARABIA("SAUDI_ARABIA", "Saudi Arabia", "사우디아라비아"),
    SAN_MARINO("SAN_MARINO", "San Marino", "산마리노"),
    SAO_TOME_AND_PRINCIPE("SAO_TOME_AND_PRINCIPE", "São Tomé and Príncipe", "상투메 프린시페"),
    WESTERN_SAHARA("WESTERN_SAHARA", "Western Sahara", "서사하라"),
    SENEGAL("SENEGAL", "Senegal", "세네갈"),
    SERBIA("SERBIA", "Serbia", "세르비아"),
    SEYCHELLES("SEYCHELLES", "Seychelles", "세이셸"),
    SAINT_LUCIA("SAINT_LUCIA", "Saint Lucia", "세인트루시아"),
    SAINT_VINCENT_AND_THE_GRENADINES("SAINT_VINCENT_AND_THE_GRENADINES", "Saint Vincent and the Grenadines", "세인트빈센트 그레나딘"),
    SAINT_KITTS_AND_NEVIS("SAINT_KITTS_AND_NEVIS", "Saint Kitts and Nevis", "세인트키츠 네비스"),
    SOMALIA("SOMALIA", "Somalia", "소말리아"),
    SOMALILAND("SOMALILAND", "Somaliland", "소말릴란드"),
    SOLOMON_ISLANDS("SOLOMON_ISLANDS", "Solomon Islands", "솔로몬 제도"),
    SUDAN("SUDAN", "Sudan", "수단"),
    SURINAME("SURINAME", "Suriname", "수리남"),
    SRI_LANKA("SRI_LANKA", "Sri Lanka", "스리랑카"),
    SWEDEN("SWEDEN", "Sweden", "스웨덴"),
    SWITZERLAND("SWITZERLAND", "Switzerland", "스위스"),
    SPAIN("SPAIN", "Spain", "스페인"),
    SLOVAKIA("SLOVAKIA", "Slovakia", "슬로바키아"),
    SLOVENIA("SLOVENIA", "Slovenia", "슬로베니아"),
    SYRIA("SYRIA", "Syria", "시리아"),
    SIERRA_LEONE("SIERRA_LEONE", "Sierra Leone", "시에라리온"),
    SINGAPORE("SINGAPORE", "Singapore", "싱가포르"),
    UNITED_ARAB_EMIRATES("UNITED_ARAB_EMIRATES", "United Arab Emirates", "아랍에미리트"),
    ARMENIA("ARMENIA", "Armenia", "아르메니아"),
    ARGENTINA("ARGENTINA", "Argentina", "아르헨티나"),
    ARTSAKH("ARTSAKH", "Artsakh", "아르차흐"),
    ICELAND("ICELAND", "Iceland", "아이슬란드"),
    HAITI("HAITI", "Haiti", "아이티"),
    IRELAND("IRELAND", "Ireland", "아일랜드"),
    AZERBAIJAN("AZERBAIJAN", "Azerbaijan", "아제르바이잔"),
    AFGHANISTAN("AFGHANISTAN", "Afghanistan", "아프가니스탄"),
    ANDORRA("ANDORRA", "Andorra", "안도라"),
    ALBANIA("ALBANIA", "Albania", "알바니아"),
    ALGERIA("ALGERIA", "Algeria", "알제리"),
    ABKHAZIA("ABKHAZIA", "Abkhazia", "압하지야"),
    ANGOLA("ANGOLA", "Angola", "앙골라"),
    ANTIGUA_AND_BARBUDA("ANTIGUA_AND_BARBUDA", "Antigua and Barbuda", "앤티가 바부다"),
    ERITREA("ERITREA", "Eritrea", "에리트레아"),
    ESWATINI("ESWATINI", "Eswatini", "에스와티니"),
    ESTONIA("ESTONIA", "Estonia", "에스토니아"),
    ECUADOR("ECUADOR", "Ecuador", "에콰도르"),
    ETHIOPIA("ETHIOPIA", "Ethiopia", "에티오피아"),
    EL_SALVADOR("EL_SALVADOR", "El Salvador", "엘살바도르"),
    UNITED_KINGDOM("UNITED_KINGDOM", "United Kingdom", "영국"),
    YEMEN("YEMEN", "Yemen", "예멘"),
    OMAN("OMAN", "Oman", "오만"),
    AUSTRIA("AUSTRIA", "Austria", "오스트리아"),
    HONDURAS("HONDURAS", "Honduras", "온두라스"),
    JORDAN("JORDAN", "Jordan", "요르단"),
    UGANDA("UGANDA", "Uganda", "우간다"),
    URUGUAY("URUGUAY", "Uruguay", "우루과이"),
    UZBEKISTAN("UZBEKISTAN", "Uzbekistan", "우즈베키스탄"),
    UKRAINE("UKRAINE", "Ukraine", "우크라이나"),
    IRAQ("IRAQ", "Iraq", "이라크"),
    IRAN("IRAN", "Iran", "이란"),
    ISRAEL("ISRAEL", "Israel", "이스라엘"),
    EGYPT("EGYPT", "Egypt", "이집트"),
    ITALY("ITALY", "Italy", "이탈리아"),
    INDIA("INDIA", "India", "인도"),
    INDONESIA("INDONESIA", "Indonesia", "인도네시아"),
    JAPAN("JAPAN", "Japan", "일본"),
    JAMAICA("JAMAICA", "Jamaica", "자메이카"),
    ZAMBIA("ZAMBIA", "Zambia", "잠비아"),
    EQUATORIAL_GUINEA("EQUATORIAL_GUINEA", "Equatorial Guinea", "적도 기니"),
    GEORGIA("GEORGIA", "Georgia", "조지아"),
    CHINA("CHINA", "China", "중국"),
    CENTRAL_AFRICAN_REPUBLIC("CENTRAL_AFRICAN_REPUBLIC", "Central African Republic", "중앙아프리카 공화국"),
    DJIBOUTI("DJIBOUTI", "Djibouti", "지부티"),
    ZIMBABWE("ZIMBABWE", "Zimbabwe", "짐바브웨"),
    CHAD("CHAD", "Chad", "차드"),
    CZECH_REPUBLIC("CZECH_REPUBLIC", "Czech Republic", "체코"),
    CHILE("CHILE", "Chile", "칠레"),
    CAMEROON("CAMEROON", "Cameroon", "카메룬"),
    CABO_VERDE("CABO_VERDE", "Cabo Verde", "카보베르데"),
    KAZAKHSTAN("KAZAKHSTAN", "Kazakhstan", "카자흐스탄"),
    QATAR("QATAR", "Qatar", "카타르"),
    CAMBODIA("CAMBODIA", "Cambodia", "캄보디아"),
    CANADA("CANADA", "Canada", "캐나다"),
    KENYA("KENYA", "Kenya", "케냐"),
    COMOROS("COMOROS", "Comoros", "코모로"),
    KOSOVO("KOSOVO", "Kosovo", "코소보"),
    COSTA_RICA("COSTA_RICA", "Costa Rica", "코스타리카"),
    COTE_DIVOIRE("COTE_DIVOIRE", "Côte d’Ivoire", "코트디부아르"),
    COLOMBIA("COLOMBIA", "Colombia", "콜롬비아"),
    REPUBLIC_OF_THE_CONGO("REPUBLIC_OF_THE_CONGO", "Republic of the Congo", "콩고 공화국"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("DEMOCRATIC_REPUBLIC_OF_THE_CONGO", "Democratic Republic of the Congo", "콩고 민주 공화국"),
    CUBA("CUBA", "Cuba", "쿠바"),
    KUWAIT("KUWAIT", "Kuwait", "쿠웨이트"),
    CROATIA("CROATIA", "Croatia", "크로아티아"),
    KYRGYZSTAN("KYRGYZSTAN", "Kyrgyzstan", "키르기스스탄"),
    KIRIBATI("KIRIBATI", "Kiribati", "키리바시"),
    CYPRUS("CYPRUS", "Cyprus", "키프로스"),
    TAJIKISTAN("TAJIKISTAN", "Tajikistan", "타지키스탄"),
    TANZANIA("TANZANIA", "Tanzania", "탄자니아"),
    THAILAND("THAILAND", "Thailand", "태국"),
    TOGO("TOGO", "Togo", "토고"),
    TONGA("TONGA", "Tonga", "통가"),
    TURKMENISTAN("TURKMENISTAN", "Turkmenistan", "투르크메니스탄"),
    TUVALU("TUVALU", "Tuvalu", "투발루"),
    TUNISIA("TUNISIA", "Tunisia", "튀니지"),
    TURKIYE("TURKIYE", "Türkiye", "튀르키예"),
    TRANSNISTRIA("TRANSNISTRIA", "Transnistria", "트란스니스트리아"),
    TRINIDAD_AND_TOBAGO("TRINIDAD_AND_TOBAGO", "Trinidad and Tobago", "트리니다드 토바고"),
    PANAMA("PANAMA", "Panama", "파나마"),
    PARAGUAY("PARAGUAY", "Paraguay", "파라과이"),
    PAKISTAN("PAKISTAN", "Pakistan", "파키스탄"),
    PAPUA_NEW_GUINEA("PAPUA_NEW_GUINEA", "Papua New Guinea", "파푸아 뉴기니아"),
    PALAU("PALAU", "Palau", "팔라우"),
    PALESTINE("PALESTINE", "Palestine", "팔레스타인"),
    PERU("PERU", "Peru", "페루"),
    PORTUGAL("PORTUGAL", "Portugal", "포르투갈"),
    POLAND("POLAND", "Poland", "폴란드"),
    FRANCE("FRANCE", "France", "프랑스"),
    FIJI("FIJI", "Fiji", "피지"),
    FINLAND("FINLAND", "Finland", "핀란드"),
    PHILIPPINES("PHILIPPINES", "Philippines", "필리핀"),
    HUNGARY("HUNGARY", "Hungary", "헝가리"),
    AUSTRALIA("AUSTRALIA", "Australia", "호주"),
    HONG_KONG("HONG_KONG", "Hong Kong", "홍콩"),
    MACAU("MACAU", "Macau", "마카오"),


    ;

    private final String dbValue;
    private final String englishName;
    private final String koreanName;

    Nationality(String dbValue, String englishName, String koreanName) {
        this.dbValue = dbValue;
        this.englishName = englishName;
        this.koreanName = koreanName;
    }

    public static Nationality getNationalityByDBValue(String dbValue){
        for(Nationality nationality : Nationality.values()){
            if(nationality.getDbValue().equals(dbValue)){
                return nationality;
            }
        }
        return null;
    }
}
